apiVersion: tekton.dev/v1
kind: Pipeline
metadata:
  name: fetch-and-print-recipe
spec:
  workspaces:
    - name: recipe-store
    - name: shared-data
  tasks:
    - name: fetch-the-recipe
      taskRef:
        name: fetch-secure-data
      workspaces:
        - name: recipe-store
        - name: shared-data
    - name: print-the-recipe
      taskRef:
        name: print-data
      runAfter:
        - fetch-the-recipe
      params:
        - name: filename
          value: recipe.txt
      workspaces:
        - name: shared-data
  results:
    - name: status
      description: status of task
      value: $(tasks.print-the-recipe.results.status)
