apiVersion: tekton.dev/v1
kind: Pipeline
metadata:
  name: fetch-and-print-recipe
spec:
  workspaces:
    - name: recipe-store
    - name: shared-data
  tasks:
    - name: fetch-the-recipe
      taskRef:
        name: fetch-secure-data
      workspaces:
        - name: recipe-store
        - name: shared-data
    - name: wait
      taskRef:
        apiVersion: openshift-pipelines.org/v1alpha1
        kind: ApprovalTask
      params:
        - name: approvers
          value:
            - user1
            - user2
        - name: numberOfApprovalsRequired
          value: 1
      runAfter:
        - fetch-the-recipe
    - name: print-the-recipe
      taskRef:
        name: print-data
      runAfter:
        - wait
      params:
        - name: filename
          value: recipe.txt
      workspaces:
        - name: shared-data
  results:
    - name: status
      description: status of task
      value: $(tasks.print-the-recipe.results.status)
